#新加任务需要把名字添加到fact_whaley.job的dependencies配置中
#详情页浏览
type=command
table=fact_whaley_detail_view
mainclass=cn.whaley.datawarehouse.fact.whaley.DetailView
command=sh ${working.dir}/../../../bin/fact_submit${frequency}.sh ${mainclass} --jobName fact_whaley_DetailView --startDate ${startDate} --endDate ${endDate} --startHour ${startHour} --endHour ${endHour}  --isOnline  ${isOnline}
#command.1=sh ${working.dir}/../../../bin/addPartition${frequency}.sh --table ${table} --startDate ${startDate} --endDate ${endDate} --startHour ${startHour} --endHour ${endHour} --isOnline  ${isOnline}
