#新加任务需要把名字添加到fact_whaley.job的dependencies配置中
#会员订单权益
type=command
table=fact_whaley_membership_process
mainclass=cn.whaley.datawarehouse.fact.whaley.MembershipProcess
command=sh ${working.dir}/../../../bin/fact_submit${frequency}.sh ${mainclass} --jobName fact_whaley_MembershipProcess --startDate ${startDate} --endDate ${endDate}  --startHour ${startHour} --endHour ${endHour} --isOnline  ${isOnline}
#command.1=sh ${working.dir}/../../../bin/addPartition${frequency}.sh --table ${table} --startDate ${startDate} --endDate ${endDate}  --startHour ${startHour} --endHour ${endHour} --isOnline  ${isOnline}
