#新加任务需要把名字添加到fact_whaley_parquet.job的dependencies配置中
#点击日志建模
type=command
table=fact_whaley_play_path_click
mainclass=cn.whaley.datawarehouse.fact.whaley.PlayPathClick
command=sh ${working.dir}/../../../bin/fact_submit${frequency}.sh ${mainclass} --jobName fact_whaley_PlayPathClick --startDate ${startDate} --endDate ${endDate} --startHour ${startHour} --endHour ${endHour}  --isOnline  ${isOnline}
#command.1=sh ${working.dir}/../../../bin/addPartition${frequency}.sh --table ${table} --startDate ${startDate} --endDate ${endDate}  --startHour ${startHour} --endHour ${endHour} --isOnline  ${isOnline}