package cn.whaley.datawarehouse.global

/**
  * Created by baozhiwang on 2017/3/7.
  */
object LogTypes {
  val ACTION = "action"
  val APPSUBJECT = "appsubject"
  val APPACCESS = "appaccess"
  val BACK = "back"
  val BUTTON = "button"
  val BUTTONCLICK = "buttonclick"
  val CLICKSEARCHRESULT = "medusa-search-clickResult"
  val COLLECT = "collect"
  val DELETECOLLECT = "deletecollect"
  val DETAIL = "detail"
  val EDITENTRANCE = "editentrance"
  val ENTER = "enter"
  val ENTRANCEVIEW = "entranceview"
  val EVALUATE = "evaluate"
  val EXIT = "exit"
  val FOCUS = "focus"
  val HOMEACCESS = "homeaccess"
  val HOMEVIEW = "homeview"
  val INPUTMETHODUSAGE = "inputmethodusage"
  val INTERVIEW = "interview"
  val KEY = "key"
  val KEYEVENT = "keyEvent"
  val KEYEVENT_KEY = "keyEvent_KEY"
  val KEYEVENT_MENU = "keyEvent_MENU"
  val LIVE = "live"
  val LIVEQOS = "liveqos"
  val LIVEBUTTON = "livebutton"
  val LIVECENTERVIEW = "livecenterview"
  val LOGIN_PROCESS = "login-process"
  val MATCHDETAIL = "matchdetail"
  val MEDUSA_MV_CLICKRESULT = "medusa-mv-clickResult"
  val MEDUSA_MV_STATION_CLICKRESULT = "medusa-mv_station-clickResult"
  val MENU = "menu"
  val MTVACCOUNT = "mtvaccount"
  val HELIOS_MTVACCOUNT = "helios_mtv_terminal"
  val PAGEVIEW = "pageview"
  val PLAY = "play"
  val PLAY_PAUSE = "play-pause"
  val PLAY_PAUSEMERGER = "play-pauseMerger"
  val PLAYQOS = "playqos"
  val PLAYVIEW = "playview"
  val POSITIONACCESS = "positionaccess"
  val SEARCH_TABVIEW = "search-tabview"
  val SEARCHENTRANCE = "searchEntrance"
  val SEARCHENTRANCE2 = "medusa-search-clickResult"
  val SELECTACCOUNT = "selectaccount"
  val SPORTSLIVEDETAIL = "sportslivedetail"
  val SPORTSSUBSCRIBE = "sportssubscribe"
  val STARTPAGE = "startpage"
  val SUBJECT = "subject"
  val SUBSCRIBE = "subscribe"
  val SWITCHINPUTMETHOD = "switchinputmethod"
  val SWITCHONOFF = "switchonoff"
  val TABVIEW = "tabview"
  val VIDEOBUTTON = "videobutton"
  val SET = "set"
  val MORETV_MTV_ACCOUNT = "moretv_mtv_account"
  val LOGINLOG = "loginlog"

  val APP_RECOMMEND = "apprecommend"
  val CLICK_ENTRANCE = "clickEntrance"
  val CLICK_RESULT = "clickResult"
  val OPERATION = "operation"
  val OPERATION_E = "operation-e"
  val OPERATION_ST = "operation-st"
  val OPERATION_MM = "operation-mm"
  val PLAY_VIEW_2_FILTER = "playview2filter"
  val PLAY_VIEW_2 = "playview2"
  val DETAIL_SUBJECT = "detail-subject"
  val SUBJECT_INTERVIEW = "subject-interview"
  val OPERATION_ACW = "operation-acw"

  val BULLETSCREEN = "bulletscreen"
  val DANMUSWITCH = "danmuswitch"
  val DANMUSTATUS = "danmustatus"

  val AREAINFO = "/log/medusa/temple/areaInfo/cityInfo/"
  val USERAREAOUTDIR = "/log/medusa/userAreaInfo/"

  val MEDUSABOOTSTARTPAGE = "medusa-boot-startpage"

  //for data warehouse
  val MEDUSA_PLAY_2X_FILTER_RESULT = "medusaPlay2xFilterResult"
  val MEDUSA_PLAY_3X_COMBINE_RESULT = "medusaPlay3xCombineResult"
}
